/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "% complete": "% 完成",
    "Active Buildings": "活跃建筑",
    "Buildings": "建筑",
    "Citizens": "市民",
    "Colony Level": "殖民地等级",
    "Colony": "殖民地",
    "Coming Soon": "敬请期待",
    "Dashboard": "仪表板",
    "Energy": "能量",
    "food": "食物",
    "Food": "食物",
    "Galactic Market": "银河市场",
    "Growth": "成长",
    "Happiness": "幸福度",
    "Hegemony Trade": "霸权贸易",
    "Menu": "菜单",
    "Market": "市场",
    "minerals": "矿物",
    "Minerals": "矿物",
    "Rank": "等级",
    "Quests": "任务",
    "resource": "资源",
    "Solars": "太阳能",
    "Supervisor": "主管",
    "XP:": "经验值:",
    "Population": "人口",
    "other quests": "其他任务",
    "No pending construction": "没有在建工程",
    "New features under development": "正在开发的新功能",
    "Influence": "影响力",
    "in decline": "衰落中",
    "Probation Quota": "试用配额",
    "Processed Resources": "已加工资源",
    "Build": "建造",
    "Level": "等级",
    "Colony Center": "殖民地中心",
    "Quota": "配额",
    "Scroll to pan • Ctrl+Scroll to zoom • Double-click to reset": "滚动平移 • 按Ctrl+滚动进行缩放 • 双击以重置",
    "(Insufficient resources)": "（资源不足）",
    "available": "可用",
    "Available Resources": "可用资源",
    "Available:": "可用:",
    "completed quests": "已完成任务",
    "Event Stories": "活动剧情",
    "events": "活动",
    "Fulfill": "满足",
    "Fulfill the first quota.": "完成第一个配额。",
    "Hegemony Quota Quests": "霸权配额任务",
    "Main": "主要",
    "Main Story": "主线剧情",
    "Max": "最大",
    "Need:": "需要:",
    "Next Scene:": "下一个场景:",
    "Quota Requirements": "配额要求",
    "resources": "资源",
    "Rising Expectations": "不断上升的预期",
    "scenes": "场景",
    "The Governor's Mantle": "总督的披风",
    "Total contribution:": "累计贡献：",
    "Active Quests": "活跃任务",
    "Continue": "继续",
    "Event": "活动",
    "Planetfall": "行星陨落",
    "SKIP TO REWARD": "跳到奖励",
    "The 'Stellar Cartographer' shudders through re-entry. Below, Gamma-9 resolves: ochre dust, rock formations, and the glint of prefab structures under a harsh sun. Your new assignment as Governor awaits.": "“恒星制图师”在重返大气层时战栗不已。下面，伽玛-9探测到：赭石尘埃，岩层，以及在烈日下闪闪发光的预制结构。等待您的是总督的新任务。",
    "Your candidacy has been evaluated against strategic resource development needs. Gamma-9 is designated for accelerated resource development with promising mineral and energy potential. Meet output targets. Progress through Sacrifice.": "您的候选资格已根据战略资源开发需求进行评估。伽马-9被指定用于加速开发具有潜力的矿物和能源资源。完成产出目标。通过牺牲取得进步。",
    "A woman emerges from an office. Administrator's uniform. Worn, but clean.": "一个女人从办公室里走出来。管理员的制服。破旧，但很干净。",
    "Council Message": "委员会的消息",
    "Direct and pragmatic. Meeting the quota is certainly our first priority. Let's get those resource extractors operational.": "直接而务实。完成配额当然是我们的首要任务。让那些资源提取器运行起来。",
    "End of scene": "场景结束",
    "Governor. You made it. Tavi Morrigan, Station Administrator.": "州长。你做到了。塔维·莫瑞根，空间站管理员。",
    "Let's prioritize the exact resources we need to deliver.": "让我们优先考虑我们需要提供的资源。",
    "New Objectives:": "新目标：",
    "Okay. Let's start with the Energy Plant.": "好吧。让我们从能源工厂开始。",
    "Rewards": "奖励",
    "She brings up a wall console. Resource levels flash warning amber: Energy, Foodstuffs, Minerals, all below optimal levels.": "她打开了一个墙上的控制台。资源水平闪烁警告琥珀色：能源，食品，矿物，均低于最佳水平。",
    "She gestures around at the spartan administrative center.": "她指了指简朴的行政中心。",
    "Tavi": "塔维",
    "Tavi waits, watching your reaction to the display with impatience.": "塔维等着，不耐烦地看着你对展品的反应。",
    "The console displays your first quota requirements: 100 units of minerals and 25 units of food.": "控制台显示你的第一个配额要求：100单位的矿物质和25单位的食物。",
    "The Countil's expectations weigh heavily. The ancient creed 'Progress through Sacrifice' means something just that bit different now.": "安理会的期望很重要。古老的信条“通过牺牲取得进步”现在的含义略有不同。",
    "This is where we stand. Not ideal. And the Hegemony has assigned your first resource quota already. We need to get moving.": "这就是我们的立场。不是最理想的。霸权已经分配了你的第一个资源配额。我们得行动了。",
    "We have basic infrastructure - minimal power generation, rudimentary housing, and essential life support.": "我们有基本的基础设施——最低限度的发电、简陋的住房和基本的生活保障。",
    "We need to develop all resources simultaneously.": "我们需要同时开发所有资源。",
    "Welcome to Gamma-9. Don't believe everything the briefing told you. Supplies have a habit of getting 're-prioritized' en route to the Outer Reach.": "欢迎来到伽马-9。不要相信简报告诉你的一切。在运送物资到外太空的途中，物资通常会被“重新排序”。",
    "What are our immediate priorities?": "我们的当务之急是什么？",
    "What exactly are we expected to produce?": "我们到底要生产什么？",
    "What resources and facilities do we currently have?": "我们目前有哪些资源和设施？",
    "With plans taking shape, you step into your role as Governor of Gamma-9.": "随着计划的成形，你将成为伽玛-9号的州长。",
    "You consider the colony's needs and the Hegemony's expectations.": "你要考虑殖民地的需求和霸权的期望。",
    "You disembark into the harsh climate. The air tastes metallic and thin. The admin center operates on emergency lighting, power conduits whining behind panels.": "你下了船，进入了恶劣的气候。空气有金属味，很稀薄。管理中心使用应急照明，电源管道在面板后发出呜呜声。",
    "You replay the recorded message for the nineteenth time.": "您第19次回放录制的消息。",
    "As the dust settles, you review your assignment: 'SECTOR GOVERNOR. ASSIGNMENT: GAMMA-9. Classification: Developing Resource Zone, Outer Reach. Priority: Accelerated resource development.'": "尘埃落定后，你回顾自己的任务：“区域长官”。作业：伽玛-9。分类：开发资源区，外延。优先事项：加快资源开发。",
    "Your initial quota is relatively modest - some minerals and food.": "你最初的配额是相对适中的 -- 一些矿物质和食物。",
    "Sensible choice. Without sufficient energy, nothing else functions efficiently. I'll help you get the construction plans ready.": "明智的选择。没有足够的能量，其他一切都无法有效运作。我会帮你把建筑计划准备好。",
    "Allow Stellar Game to save your progress locally on this device? This will ensure you never lose your hard-earned resources and colony progress.": "允许恒星游戏本地保存您的进度在这个设备上？这将确保你永远不会失去你来之不易的资源和殖民地的进展。",
    "As you meet quotas, you'll unlock new building types, quests, and narratives. Expand your colony wisely to handle increasing demands from the Hegemony.": "当你达到配额时，你将解锁新的建筑类型，任务和故事。明智地扩展你的殖民地，以应对来自霸权的日益增长的需求。",
    "Begin Colony Development": "开始殖民地发展",
    "Building Interface": "建筑界面",
    "Colony Growth": "殖民地成长",
    "Colony Management: Getting Started": "殖民地管理：入门",
    "Don't forget about your colonists. Housing, food, and other conditions affect their growth.": "别忘了你的殖民者。住房、食物和其他条件都会影响它们的生长。",
    "Enable Game Saves?": "启用游戏保存？",
    "Enable Saves": "启用保存",
    "Meeting Quotas": "会议配额",
    "Mineral Extractor": "矿物提取器",
    "Navigate to the 'Colony' tab to construct essential infrastructure. Each building requires energy to operate efficiently.": "导航到“殖民地”选项卡来建造必要的基础设施。每座建筑都需要能源才能有效运行。",
    "Next": "下一个",
    "Not Now": "不是现在",
    "Population Management": "人口管理",
    "Resource Production": "资源生产",
    "The Hegemony requires regular resource deliveries from your colony. Check your current quota requirements in the 'Quests' tab under 'Hegemony Quota Quests'.": "霸权需要定期从你的殖民地运送资源。在“霸权配额任务”下的“任务”选项卡中检查您当前的配额要求。",
    "Welcome to Gamma-9": "欢迎来到伽马-9",
    "Welcome to your new colony, Governor! As the appointed governor, you'll need to build and manage this outpost to meet Hegemony expectations.": "欢迎来到你的新殖民地，总督！作为指定的总督，你需要建造和管理这个前哨站，以满足霸权的期望。",
    "Your game data is stored only on this device and is never sent to our servers.": "您的游戏数据仅存储在此设备上，不会发送到我们的服务器。",
    "Your primary goal is resource production. Start by constructing an Energy Plant  and Hydroponic Farm to establish your basic production chain.": "你的主要目标是资源生产。从建造一个能源工厂和水培农场开始，建立你的基本生产链。",
    "A well-rounded approach should work. We'll need to be careful with resource allocation, but it could pay off if we execute well.": "一个全面的方法应该会起作用。我们需要谨慎地分配资源，但如果我们执行得好，就会得到回报。",
    "Are you sure you want to contribute 83 resources to this quota? This action cannot be undone.": "确定为该配额贡献83个资源吗？此操作不能撤消。",
    "Base Production Rates": "基本生产速率",
    "Cancel": "取消",
    "Colonist": "殖民者",
    "Confirm Fulfillment": "确认完成",
    "Consumption": "消耗",
    "Demolish Building": "拆除建筑",
    "Effects": "影响",
    "Energy Storage": "能量储存",
    "Extracts raw mineral resources from the planet's crust.": "从地壳中提取原始矿物资源。",
    "Food Storage": "储存食物",
    "Housing Capacity": "住房的能力",
    "Minerals Storage": "矿物存储",
    "next lvl": "下一个级",
    "Not enough resources": "资源不足",
    "Select a quest to view details": "选择一个任务以查看详细信息",
    "The heart of your colony, providing essential infrastructure.": "你们殖民地的中心，提供必要的基础设施。",
    "Upgrade Costs": "升级成本",
    "Workers": "工人",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "s": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "GAMMA-": "伽马-",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " to next rank)": " 到下一级)",
    " at next level)": " 在下一级)",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);